default:
        image: shreyas911/sicopolis_ad_v2:v1.4

stages:
        - test

tests:
        stage: test
        only:
               - develop
        before_script:
               - export NETCDF_F90_FLAG=-I/usr/include
               - export LISDIR=/lis-2.0.30/installation
               - export LIB_NETCDF_F90_FLAG='-L/usr/lib/x86_64-linux-gnu -lnetcdff'
               - export TAPENADE_HOME=/builds/sicopolis/sicopolis/test_ad/tapenade_supported
               - export PATH=$PATH:$TAPENADE_HOME/bin
               - pwd
               - ls -a ./*
               - echo $PATH
               - echo $TAPENADE_HOME
               - source $HOME/.bashrc
        script:
               - ./get_input_files.sh
               - cd test_ad
               - cp headers/* ../headers
               - cp headers_ad/templates/* headers_ad
               - pytest tests_asi.py tests_bsi.py
